### ISSUE TITLE
Error when starting a new fit

### ISSUE THREAD

**Issue by AEB-5-47** [diffpy/diffpy.pdfgui#234]
Error message as follows when trying to load data/phase for a new fit:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/pdfgui2-intel/lib/python3.9/site-packages/diffpy/pdfgui/gui/errorwrapper.py", line 62, in _f
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/pdfgui2-intel/lib/python3.9/site-packages/diffpy/pdfgui/gui/addphasepanel.py", line 106, in readConfiguration
    remember = self.cP.getboolean("PHASE", "remember")
  File "/opt/anaconda3/envs/pdfgui2-intel/lib/python3.9/configparser.py", line 828, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "/opt/anaconda3/envs/pdfgui2-intel/lib/python3.9/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/opt/anaconda3/envs/pdfgui2-intel/lib/python3.9/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/opt/anaconda3/envs/pdfgui2-intel/lib/python3.9/configparser.py", line 1166, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: ['False', '']

**Comment by Tieqiong** [comment]
Hello!
May I ask what kind of data/phase you are adding? 

Also if possible please go to your user folder and there should be a hidden file called `.pdfgui_py3.cfg`. Open the file with a text editor and look for the field "[PHASE]". I suspect in the list under this field there's one `remember` that don't have a corresponding value. I'd say by giving it a proper `boolean` value (e.g. `False`) will solve the problem. If not, there's always the option of reinstall the program.

Hope this helps!

**Comment by AEB-5-47** [comment]
@Tieqiong, it happened when selecting either the insert new data insert new phase.
I do seem to be able to continue the fit as normal if I just cancel the error message (now I have also reinstalled).

**Comment by sbillinge** [comment]
Let's try and test whether this goes away in the `3.1.0rc` release.  I'm therefore moving this issue to the `3.1.0 full release` milestone.

**Comment by sbillinge** [comment]
@AEB-5-47 please could you see if you can reproduce this bug in the latest version of the code?  We have a pre-release version that we are testing.  

To install it, please use these instructions:

Installation instructions (Windows, Linux, macOS non-arm64):
```
conda create -n pdfgui313rc python=3.13
conda activate pdfgui313rc
conda install wxpython diffpy.utils diffpy.pdffit2 matplotlib-base pycifrw
pip install diffpy.pdfgui==3.1.0rc8 --no-deps
```
Instructions for Mac-OS arm64:
```
conda create -n pdfgui313rc python=3.13
conda activate pdfgui313rc
conda install wxpython diffpy.utils matplotlib-base pycifrw
pip install diffpy.pdffit2
pip install diffpy.pdfgui==3.1.0rc8 --no-deps
```

Thanks so much!

**Comment by AEB-5-47** [comment]
@sbillinge the bug has been resolved! Excellent.
I also really like the new look of the PDF plot!

**Comment by AEB-5-47** [comment]
@sbillinge I have noticed an issue with the plot feature. In plotting the Gtrunc of two data sets (r on the x axis), it labels the data sets the wrong way around.

**Comment by sbillinge** [comment]
> [@sbillinge](https://github.com/sbillinge) the bug has been resolved! Excellent. I also really like the new look of the PDF plot!

Thanks so much. It is using `bg-mpl-stylesheets` colors now.  This is our group matplotlib stylesheet.  Anyone can can conda install it and import it and use it if they like.  Instructions are here: https://github.com/Billingegroup/bg-mpl-stylesheets

**Comment by sbillinge** [comment]
> [@sbillinge](https://github.com/sbillinge) I have noticed an issue with the plot feature. In plotting the Gtrunc of two data sets (r on the x axis), it labels the data sets the wrong way around.

wow, great catch!  I am moving this to a new issue and closing this one as completed.
