### ISSUE TITLE
Module import error when trying to run pdfgui

### ISSUE THREAD

**Issue by saurabh02** [diffpy/diffpy.pdfgui#26]
Hello,

I install diffpy on my Mac OS Sierra, and when trying to run pdfgui from the command line, I get the below traceback. Is this related to the `wxGlade` package or another package I may be missing?

Traceback (most recent call last):
  File "/Users/sbajaj/Library/Python/2.7/bin/pdfgui", line 9, in <module>
    load_entry_point('diffpy.pdfgui==1.1.2', 'gui_scripts', 'pdfgui')()
  File "/Users/sbajaj/Library/Python/2.7/lib/python/site-packages/diffpy/pdfgui/applications/pdfgui.py", line 116, in main
    import diffpy.pdfgui.gui.Main as guimain
  File "/Users/sbajaj/Library/Python/2.7/lib/python/site-packages/diffpy/pdfgui/gui/Main.py", line 19, in <module>
    import wx
ImportError: No module named wx

Thank you
Saurabh

**Comment by pavoljuhas** [comment]
@saurabh02 - this happens when wxpython is not installed.  Please install that package and try again.  If you have several Python installations on your machine, make sure PDFgui gets installed for the Python that has wx.
