### ISSUE TITLE
ddp project files compatible problem between py2 and py3

### ISSUE THREAD

**Issue by dragonyanglong** [diffpy/diffpy.pdfgui#46]
- [x] Use py3 pdfgui to save a ddp file, then use py2 pdfgui to open it.
- [ ] vice versa

**Comment by dragonyanglong** [comment]
Hi @aPeter1, I will provide the pickel .ddp files for you in the following.

**Comment by dragonyanglong** [comment]
But the second case doesn't work properly (use the py3 pdfgui to open the py2 saved ddp file). You can find more detailed information about the pickel propotols in the PR commits #42 .

**Comment by dragonyanglong** [comment]
I tried some py2 ddp files. And it seems like some can be opened successully, but some still couldn't, and raise error as
```
Traceback (most recent call last):
  File "/Users/Dragon/Documents/Billinge/dev/diffpy.pdfgui/src/diffpy/pdfgui/gui/errorwrapper.py", line 59, in _f
    return func(*args, **kwargs)
  File "/Users/Dragon/Documents/Billinge/dev/diffpy.pdfgui/src/diffpy/pdfgui/gui/mainframe.py", line 2132, in onOpen
    treelist = self.control.load(fullpath)
  File "/Users/Dragon/Documents/Billinge/dev/diffpy.pdfgui/src/diffpy/pdfgui/control/pdfguicontrol.py", line 404, in load
    org = fit.load(z, projName + '/' + rdname + '/')
  File "/Users/Dragon/Documents/Billinge/dev/diffpy.pdfgui/src/diffpy/pdfgui/control/fitting.py", line 206, in load
    return Organizer.load(self, z, subpath)
  File "/Users/Dragon/Documents/Billinge/dev/diffpy.pdfgui/src/diffpy/pdfgui/control/organizer.py", line 157, in load
    struc.load(z, subpath + 'structure/' + strucName + '/')
  File "/Users/Dragon/Documents/Billinge/dev/diffpy.pdfgui/src/diffpy/pdfgui/control/fitstructure.py", line 776, in load
    self.custom_spacegroup = CtrlUnpickler.loads(spkl)
  File "/Users/Dragon/Documents/Billinge/dev/diffpy.pdfgui/src/diffpy/pdfgui/control/pdfguicontrol.py", line 564, in loads
    return pickle.loads(s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 22: ordinal not in range(128)
```


- ddp files that works: ddp files at the `doc/tutorial` folder.
- cryostat Ho2Ti2O7_0_60A.ddp or BFTO_Pm-3m.ddp (ask Long for the file)

**Comment by dragonyanglong** [comment]
ref: https://rebeccabilbro.github.io/convert-py2-pickles-to-py3/
