### ISSUE TITLE
multi-select a few cells

### ISSUE THREAD

**Issue by dragonyanglong** [diffpy/diffpy.pdfgui#48]
Select several cells in phase panel. If Press “shift” and select a few cells, it works fine. But if press “control” (or “command” in mac) on keyboard, click a few cells. it shows:
```
Traceback (most recent call last):
  File "/home/ly0/Documents/billinge/dev/test_pdfgui_py3/diffpy.pdfgui/src/diffpy/pdfgui/gui/errorwrapper.py", line 59, in _f
    return func(*args, **kwargs)
  File "/home/ly0/Documents/billinge/dev/test_pdfgui_py3/diffpy.pdfgui/src/diffpy/pdfgui/gui/phaseconfigurepanel.py", line 453, in onEditorShown
    self._selectedCells = gridutils.getSelectedCells(self.gridAtoms)
  File "/home/ly0/anaconda3/envs/pdfgui_py37_test/lib/python3.7/site-packages/diffpy.utils-3.0.0-py3.7.egg/diffpy/utils/wx/gridutils.py", line 78, in getSelectedCells
    rcset.update(grid.GetSelectedCells())
TypeError: unhashable type: 'GridCellCoords'
```

**Comment by dragonyanglong** [comment]
https://github.com/wxWidgets/Phoenix/issues/319

**Comment by dragonyanglong** [comment]
In the `gridutils.py` file, only one line is changed from py2 (right) to py3 (left).

![image](https://user-images.githubusercontent.com/16789768/142753124-0a56fcb3-f34d-437c-9005-d46b58face70.png)

**Comment by dragonyanglong** [comment]
Temporary solution: comment out the problematic line of code (L78). It will not affect the working `column` or `row` selection.
Side effect: press "control" (or command in mac) and select multi-cells, will only change the value of the first cell selected.

![image](https://user-images.githubusercontent.com/16789768/142753232-493a800c-2051-4ba9-b7f9-fe81c1daf7bb.png)

**Comment by dragonyanglong** [comment]
- [ ] post an issue to wxpython github.
- [ ] remove the temporary fix and revert back to show error message.
- [ ] show a user friendly error message.
