### ISSUE TITLE
ImportError when calling pdfgui from WSL terminal

### ISSUE THREAD

**Issue by maak-sdu** [diffpy/diffpy.pdfgui#55]
Followed the guidelines at https://www.diffpy.org/products/pdfgui.html to install pdfgui within its own conda env in a WSL (Windows Subsystem for Linux) terminal. Trying to run pdfgui, the following error is encountered (the whole installation process is attached as a .txt file):

(py27) maak@ADM-126243:~$ pdfgui
Traceback (most recent call last):
  File "/home/maak/miniconda3/envs/py27/bin/pdfgui", line 11, in <module>
    sys.exit(main())
  File "/home/maak/miniconda3/envs/py27/lib/python2.7/site-packages/diffpy.pdfgui-1.1.2-py2.7.egg/diffpy/pdfgui/applications/pdfgui.py", line 116, in main
    import diffpy.pdfgui.gui.Main as guimain
  File "/home/maak/miniconda3/envs/py27/lib/python2.7/site-packages/diffpy.pdfgui-1.1.2-py2.7.egg/diffpy/pdfgui/gui/Main.py", line 19, in <module>
    import wx
  File "/home/maak/miniconda3/envs/py27/lib/python2.7/site-packages/wx-3.0-gtk2/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/home/maak/miniconda3/envs/py27/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

[WSL_pdfgui_error.txt](https://github.com/diffpy/diffpy.pdfgui/files/6437454/WSL_pdfgui_error.txt)

**Comment by sbillinge** [comment]
closing as no longer relevant.  We are not supporting py2.7 any more.
