### ISSUE TITLE
Problem with pdfgui 2.0 

### ISSUE THREAD

**Issue by LalitYadav07** [diffpy/diffpy.pdfgui#95]
I have started to get this error as soon as i right click to put constraints:
```
Traceback (most recent call last):
  File "/Users/swatisahu/opt/anaconda3/envs/pdfgui2/lib/python3.9/site-packages/diffpy/pdfgui/gui/errorwrapper.py", line 62, in _f
    return func(*args, **kwargs)
  File "/Users/swatisahu/opt/anaconda3/envs/pdfgui2/lib/python3.9/site-packages/diffpy/pdfgui/gui/phaseconstraintspanel.py", line 540, in onPopupSpaceGroup
    dlg = SGConstrainDialog(self)
  File "/Users/swatisahu/opt/anaconda3/envs/pdfgui2/lib/python3.9/site-packages/diffpy/pdfgui/gui/sgconstraindialog.py", line 44, in __init__
    self.__do_layout()
  File "/Users/swatisahu/opt/anaconda3/envs/pdfgui2/lib/python3.9/site-packages/diffpy/pdfgui/gui/sgconstraindialog.py", line 82, in __do_layout
    sizer_2.Add(self.tfCheckBox, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at /Users/runner/miniforge3/conda-bld/wxpython_1616628571745/work/ext/wxWidgets/src/common/sizer.cpp(2147) in DoInsert(): Vertical alignment flags are ignored in vertical sizers
```
-----------
I have tried to install this on both macbook and windows and I have seeing this error for fresh project as soon as i click symmetry constraints. Interestingly everything was fine untill friday night and from yesterday I have started to see this error.

**Comment by dragonyanglong** [comment]
Dear @LalitYadav07 , thanks for reporting the issue. We have just fixed it. Please try updating your pdfgui version into v2.0.2 and try again. You may run `conda install -c conda-forge diffpy.pdfgui` in the same environment to update it.

Please let us know if any further problems.
